#include "Polygon.hpp"
#include "Triangle.hpp"
#include "Triangulation.hpp"

namespace graphics {

Polygon::Polygon(const std::vector<Coordinates2D>& points, const Color& color)
    : mPoints(points) {}

void Polygon::SetPoints(const std::vector<Coordinates2D>& points) {
  mPoints = points;
}

const std::vector<Coordinates2D>& Polygon::GetPoints() const {
  return mPoints;
}


void Polygon::Draw() {
  // Draw each triangle generated by the triangulation
  auto triangles=PerformTriangulation();
  for (auto triangle : triangles) {
    triangle.Draw();
  }
}

const std::vector<Triangle> Polygon::PerformTriangulation() {
  // Create a Triangulation object and perform the triangulation
  Triangulation triangulation(mPoints, mColor);
  
  // Get the resulting triangles
  return triangulation.GetTriangles();
}


}  // namespace graphics
